package de.autoapp.shared.domain

data class Network(
    val key: String,
    val name: String,
    val operatorIds: Set<Long>,
    val nameKeywords: Set<String>,
)

/**
 * The curated, shipped list of selectable charging networks — bundled so the
 * picker is populated on first launch, offline. Mirrors [VehicleCatalog]: a
 * maintained in-source list, updated by app release.
 *
 * Not the same as [de.autoapp.shared.data.OperatorCatalog], which reads
 * operator names already in the local cache.
 *
 * The first 37 rows are hand-curated (brand-merged, hand-keyed keywords).
 * The remainder are auto-generated singletons for every OCM operator with
 * >= 2 POIs in the European sample (AT/BE/CH/DE/ES/FR/GB/IT/NL/NO/SE),
 * sorted by descending POI count, junk/placeholder IDs excluded.
 */
object NetworkCatalog {

    /** Coverage/selection sentinel: no filter, fetch everything (as today). */
    const val UNFILTERED = "*"

    val all: List<Network> = listOf(
        Network("shell-recharge", "Shell Recharge",
            setOf(47L, 156L, 157L, 3392L, 3508L, 3709L, 3964L),
            setOf("shell")),
        Network("enel-x", "Enel X",
            setOf(80L),
            setOf("enel", "enelx")),
        Network("tesla", "Tesla",
            setOf(23L, 3534L),
            setOf("tesla", "supercharger")),
        Network("evbox", "EVBox",
            setOf(73L),
            setOf("evbox")),
        Network("evnet-nl", "EVnetNL",
            setOf(178L),
            setOf("evnet", "evnetnl")),
        Network("bp-pulse", "BP Pulse",
            setOf(32L, 2247L),
            setOf("bp", "pulse", "bpulse", "iberdrola")),
        Network("allego", "Allego",
            setOf(103L),
            setOf("allego")),
        Network("power-dot", "Power Dot",
            setOf(3538L, 3550L),
            setOf("powerdot", "power dot")),
        Network("izivia", "Izivia (Sodetrel)",
            setOf(213L),
            setOf("izivia", "sodetrel")),
        Network("be-charge", "Be Charge",
            setOf(3327L),
            setOf("becharge", "be charge")),
        Network("surecharge", "SureCharge (FM Conway)",
            setOf(3612L),
            setOf("surecharge", "conway")),
        Network("repsol-ibil", "Repsol-Ibil",
            setOf(91L),
            setOf("repsol", "ibil")),
        Network("char-gy", "Char.gy",
            setOf(3345L),
            setOf("chargy", "char.gy")),
        Network("totalenergies", "TotalEnergies",
            setOf(25L, 3447L, 3571L),
            setOf("total", "totalenergies")),
        Network("endesa", "Endesa",
            setOf(207L),
            setOf("endesa")),
        Network("mobive", "MObiVE",
            setOf(3407L),
            setOf("mobive")),
        Network("ladenetz", "ladenetz.de",
            setOf(69L),
            setOf("ladenetz")),
        Network("enbw", "EnBW",
            setOf(86L),
            setOf("enbw")),
        Network("pod-point", "POD Point",
            setOf(3L),
            setOf("podpoint", "pod point")),
        Network("electra", "Electra",
            setOf(3489L),
            setOf("electra")),
        Network("innogy-rwe", "Innogy SE (RWE eMobility)",
            setOf(105L),
            setOf("innogy", "rwe")),
        Network("zunder", "Zunder",
            setOf(3324L),
            setOf("zunder")),
        Network("ionity", "Ionity",
            setOf(3299L),
            setOf("ionity")),
        Network("eon-drive", "E.ON Drive",
            setOf(46L, 3251L, 3359L, 3403L, 3422L, 3814L),
            setOf("eon", "e.on", "eondrive")),
        Network("osprey", "Osprey Charging",
            setOf(203L),
            setOf("osprey")),
        Network("atlante", "Atlante",
            setOf(3588L),
            setOf("atlante")),
        Network("lidl", "Lidl",
            setOf(38L),
            setOf("lidl")),
        Network("ewe-go", "EWE Go",
            setOf(127L),
            setOf("ewe", "ewego")),
        Network("chargepoint", "ChargePoint",
            setOf(5L),
            setOf("chargepoint")),
        Network("freshmile", "Freshmile",
            setOf(3379L),
            setOf("freshmile")),
        Network("alperia", "Alperia",
            setOf(164L),
            setOf("alperia")),
        Network("smatrics", "SMATRICS",
            setOf(3253L),
            setOf("smatrics")),
        Network("ewiva", "Ewiva",
            setOf(3720L),
            setOf("ewiva")),
        Network("fastned", "FastNed",
            setOf(74L),
            setOf("fastned")),
        Network("mer", "MER (Vattenfall InCharge)",
            setOf(108L, 3492L),
            setOf("mer", "vattenfall", "incharge")),
        Network("fortum-recharge", "Recharge (Fortum)",
            setOf(198L, 202L),
            setOf("fortum", "charge and drive")),
        Network("grønn-kontakt", "Grønn Kontakt",
            setOf(3247L),
            setOf("grønn", "gronn", "gronnkontakt")),
        Network("mercadona", "Mercadona",
            setOf(3499L),
            setOf("mercadona")),
        Network("acciona-cargacoches", "ACCIONA - Cargacoches",
            setOf(3459L),
            setOf("accionacargacoches")),
        Network("essent-nl", "Essent",
            setOf(78L),
            setOf("essentnl")),
        Network("etecnic", "eTecnic",
            setOf(3377L),
            setOf("etecnic")),
        Network("wenea", "Wenea",
            setOf(3371L),
            setOf("wenea")),
        Network("eranovum-es", "Eranovum",
            setOf(3583L),
            setOf("eranovumes")),
        Network("connected-kerb", "Connected Kerb",
            setOf(3509L),
            setOf("connectedkerb")),
        Network("chargeplace-scotland", "Chargeplace Scotland",
            setOf(3315L),
            setOf("chargeplacescotland")),
        Network("believ", "Believ",
            setOf(3511L),
            setOf("believ")),
        Network("stromnetz-hamburg", "Stromnetz Hamburg",
            setOf(220L),
            setOf("stromnetzhamburg")),
        Network("ecotap", "Ecotap",
            setOf(179L),
            setOf("ecotap")),
        Network("plenergy-es", "Plenergy",
            setOf(3750L),
            setOf("plenergyes")),
        Network("comfortcharge", "Comfortcharge",
            setOf(3369L),
            setOf("comfortcharge")),
        Network("melib-es", "MELIB",
            setOf(3283L),
            setOf("melibes")),
        Network("edp", "EDP",
            setOf(3276L),
            setOf("edp")),
        Network("galp-electric", "GALP Electric",
            setOf(3557L),
            setOf("galpelectric")),
        Network("sydego", "Sydego",
            setOf(3412L),
            setOf("sydego")),
        Network("powergo", "PowerGo",
            setOf(3632L),
            setOf("powergo")),
        Network("zapgrid", "ZapGrid",
            setOf(3328L),
            setOf("zapgrid")),
        Network("place-to-plug", "Place To Plug",
            setOf(3556L),
            setOf("placetoplug")),
        Network("blue-corner-belgium", "Blue Corner (Belgium)",
            setOf(36L),
            setOf("bluecornerbelgium")),
        Network("roam-charging-uk", "Roam Charging",
            setOf(3562L),
            setOf("roamcharginguk")),
        Network("n-ergie", "N-ERGIE",
            setOf(234L),
            setOf("nergie")),
        Network("trojan-energy", "Trojan Energy",
            setOf(3738L),
            setOf("trojanenergy")),
        Network("duferco-energie", "Duferco Energie",
            setOf(3267L),
            setOf("dufercoenergie")),
        Network("the-geniepoint-network-equans-ev-solutions", "The GeniePoint Network ( EQUANS EV Solutions )",
            setOf(150L),
            setOf("thegeniepointnetworkequansevsolutions")),
        Network("moeve-es", "Moeve",
            setOf(3584L),
            setOf("moevees")),
        Network("engie", "Engie",
            setOf(3595L),
            setOf("engie")),
        Network("e-moving-italy", "E-moving (Italy)",
            setOf(82L),
            setOf("emovingitaly")),
        Network("greenflux", "Greenflux",
            setOf(63L),
            setOf("greenflux")),
        Network("remo-mobility-es", "REMO Mobility",
            setOf(3798L),
            setOf("remomobilityes")),
        Network("stadtwerke-clausthal-zellerfeld", "Stadtwerke Clausthal-Zellerfeld",
            setOf(162L),
            setOf("stadtwerkeclausthalzellerfeld")),
        Network("eborn", "eborn",
            setOf(3408L),
            setOf("eborn")),
        Network("nuon", "Nuon",
            setOf(177L),
            setOf("nuon")),
        Network("electric-highway-uk", "Electric Highway",
            setOf(24L),
            setOf("electrichighwayuk")),
        Network("free-to-x", "Free To X",
            setOf(3503L),
            setOf("freetox")),
        Network("virta", "VIRTA",
            setOf(136L),
            setOf("virta")),
        Network("pfalzwerke", "Pfalzwerke",
            setOf(1240L),
            setOf("pfalzwerke")),
        Network("charge-your-car", "Charge Your Car",
            setOf(20L),
            setOf("chargeyourcar")),
        Network("e-wald", "E-Wald",
            setOf(189L),
            setOf("ewald")),
        Network("evpass-ch", "EVPass",
            setOf(3272L),
            setOf("evpassch")),
        Network("instavolt-ltd", "InstaVolt Ltd",
            setOf(3296L),
            setOf("instavolt")),
        Network("repower-italy", "Repower (Italy)",
            setOf(3330L),
            setOf("repoweritaly")),
        Network("evolt-network-swarco-e-connect", "Evolt Network (Swarco E.Connect)",
            setOf(3341L),
            setOf("evoltnetworkswarcoeconnect")),
        Network("tanke-wien-energie", "TANKE Wien Energie",
            setOf(142L),
            setOf("tankewienenergie")),
        Network("bump-fr", "Bump",
            setOf(3661L),
            setOf("bumpfr")),
        Network("qovoltis", "Qovoltis",
            setOf(3495L),
            setOf("qovoltis")),
        Network("theplugincompany-belgium", "ThePluginCompany (Belgium)",
            setOf(35L),
            setOf("theplugincompanybelgium")),
        Network("umbrella-emobility-es", "Umbrella eMobility",
            setOf(3786L),
            setOf("umbrellaemobilityes")),
        Network("evway", "Evway",
            setOf(3291L),
            setOf("evway")),
        Network("heraricarica-pubblica", "HeraRicarica Pubblica",
            setOf(3440L),
            setOf("heraricaricapubblica")),
        Network("wroom", "Wroom",
            setOf(3382L),
            setOf("wroom")),
        Network("enercity", "EnerCity",
            setOf(121L),
            setOf("enercity")),
        Network("weev", "Weev",
            setOf(3578L),
            setOf("weev")),
        Network("be-energised-has-to-be", "Be Energised (has-to-be)",
            setOf(3261L),
            setOf("beenergisedhastobe")),
        Network("powy", "POWY",
            setOf(3586L),
            setOf("powy")),
        Network("mfg-ev-power", "MFG EV Power",
            setOf(3471L),
            setOf("mfgevpower")),
        Network("gridserve", "GridServe",
            setOf(3430L),
            setOf("gridserve")),
        Network("joju-ltd", "Joju Ltd",
            setOf(3393L),
            setOf("joju")),
        Network("mobilize-fr", "Mobilize",
            setOf(3944L),
            setOf("mobilizefr")),
        Network("nextcharge", "NEXTCHARGE",
            setOf(3657L),
            setOf("nextcharge")),
        Network("aldi-sud-de", "ALDI SÜD",
            setOf(3464L),
            setOf("aldisudde")),
        Network("naturenergie-de", "Naturenergie",
            setOf(224L),
            setOf("naturenergiede")),
        Network("amb-area-metropolitana-de-barcelona", "AMB",
            setOf(3305L),
            setOf("ambareametropolitanadebarcelona")),
        Network("alize-liberte", "Alizé Liberté",
            setOf(3410L),
            setOf("alizeliberte")),
        Network("e-motum-fr", "e-motum",
            setOf(3840L),
            setOf("emotumfr")),
        Network("silverstone-green-energy", "Silverstone Green Energy",
            setOf(3615L),
            setOf("silverstonegreenenergy")),
        Network("iecharge-fr", "IECharge",
            setOf(3639L),
            setOf("iechargefr")),
        Network("driwe", "Driwe",
            setOf(3332L),
            setOf("driwe")),
        Network("emobitaly-italy", "Emobitaly (Italy)",
            setOf(3282L),
            setOf("emobitalyitaly")),
        Network("carrefour-es", "Carrefour",
            setOf(3960L),
            setOf("carrefoures")),
        Network("telepark-empark", "Telepark (Empark)",
            setOf(3559L),
            setOf("teleparkempark")),
        Network("qwello", "Qwello",
            setOf(3809L),
            setOf("qwello")),
        Network("westfalen-weser-netz", "Westfalen Weser Netz",
            setOf(3423L),
            setOf("westfalenwesernetz")),
        Network("stadtwerke-dusseldorf-ag", "Stadtwerke Düsseldorf AG",
            setOf(235L),
            setOf("stadtwerkedusseldorf")),
        Network("incharge-se", "Incharge",
            setOf(3343L),
            setOf("inchargese")),
        Network("electroad-uk", "ElectRoad",
            setOf(3740L),
            setOf("electroaduk")),
        Network("entega", "Entega",
            setOf(3297L),
            setOf("entega")),
        Network("ovag-energie", "OVAG Energie",
            setOf(188L),
            setOf("ovagenergie")),
        Network("prioe", "PRIOE",
            setOf(200L),
            setOf("prioe")),
        Network("acea-it", "Acea",
            setOf(3525L),
            setOf("aceait")),
        Network("monta", "Monta",
            setOf(3479L),
            setOf("monta")),
        Network("rheinenergie-ag", "RheinEnergie AG",
            setOf(72L),
            setOf("rheinenergie")),
        Network("bonpreuesclat", "BonpreuEsclat",
            setOf(3945L),
            setOf("bonpreuesclat")),
        Network("fuuse", "Fuuse",
            setOf(3673L),
            setOf("fuuse")),
        Network("a2a-emoving-it", "a2a emoving",
            setOf(3728L),
            setOf("a2aemovingit")),
        Network("plugsurfing", "PlugSurfing",
            setOf(3266L),
            setOf("plugsurfing")),
        Network("leap24-nl", "Leap24",
            setOf(3504L),
            setOf("leap24nl")),
        Network("aena-ev-es", "AENA EV",
            setOf(3956L),
            setOf("aenaeves")),
        Network("fenie-energia-spain", "Fenie Energía (Spain)",
            setOf(3279L),
            setOf("fenieenergiaspain")),
        Network("da-emobil", "da emobil",
            setOf(3320L),
            setOf("daemobil")),
        Network("evite-ch", "EVite (ch)",
            setOf(110L),
            setOf("evitech")),
        Network("bartergo-es", "BarterGo",
            setOf(3552L),
            setOf("bartergoes")),
        Network("clenergy", "Clenergy",
            setOf(3605L),
            setOf("clenergy")),
        Network("ezo-ie", "EZO",
            setOf(1241L),
            setOf("ezoie")),
        Network("esb-energy-uk", "ESB Energy",
            setOf(3357L),
            setOf("esbenergyuk")),
        Network("emovili-fast-es", "emovili Fast",
            setOf(3889L),
            setOf("emovilifastes")),
        Network("city-ev", "City EV",
            setOf(3349L),
            setOf("cityev")),
        Network("eam", "EAM",
            setOf(140L),
            setOf("eam")),
        Network("electrodrive-mark-e-de", "ElectroDrive/Mark-E",
            setOf(184L),
            setOf("electrodrivemarkede")),
        Network("evn-bulgaria", "EVN (Bulgaria)",
            setOf(3616L),
            setOf("evnbulgaria")),
        Network("electric-55-charging-fr", "Electric 55 Charging",
            setOf(3513L),
            setOf("electric55chargingfr")),
        Network("be-ev", "Be.EV",
            setOf(3481L),
            setOf("beev")),
        Network("ubitricity", "ubitricity",
            setOf(2244L),
            setOf("ubitricity")),
        Network("e-vadea", "e-Vadea",
            setOf(3594L),
            setOf("evadea")),
        Network("move-ch", "MOVE",
            setOf(3274L),
            setOf("movech")),
        Network("stadtwerke-leipzig-swl", "Stadtwerke Leipzig SWL",
            setOf(155L),
            setOf("stadtwerkeleipzigswl")),
        Network("sde76-fr", "SDE76",
            setOf(3262L),
            setOf("sde76fr")),
        Network("iplanet-it", "iPlanet",
            setOf(3908L),
            setOf("iplanetit")),
        Network("swisscharge-ch", "Swisscharge",
            setOf(3273L),
            setOf("swisschargech")),
        Network("gofast-gotthard-fastcharge", "GOFAST (Gotthard Fastcharge)",
            setOf(3313L),
            setOf("gofastgotthardfastcharge")),
        Network("last-mile-solutions", "Last Mile Solutions",
            setOf(3387L),
            setOf("lastmilesolutions")),
        Network("ze-mo-be", "ZE-MO (Be)",
            setOf(54L),
            setOf("zemobe")),
        Network("plenitude-on-the-road-eu", "Plenitude On The Road",
            setOf(3996L),
            setOf("plenitudeontheroadeu")),
        Network("tiwag-tiroler-wasserkraft-ag-at", "TIWAG Tiroler Wasserkraft AG",
            setOf(18L),
            setOf("tiwagtirolerwasserkraftat")),
        Network("eins", "eins",
            setOf(2243L),
            setOf("eins")),
        Network("gc-movilidad-electrica-es", "GC Movilidad Electrica",
            setOf(3930L),
            setOf("gcmovilidadelectricaes")),
        Network("cel-toda-navarra-es", "CEL TODA Navarra",
            setOf(3949L),
            setOf("celtodanavarraes")),
        Network("evcharge-online", "evcharge.online",
            setOf(3295L),
            setOf("evchargeonline")),
        Network("metropolis", "Métropolis",
            setOf(3490L),
            setOf("metropolis")),
        Network("agsm-electrify-verona-it", "AGSM Electrify Verona",
            setOf(118L),
            setOf("agsmelectrifyveronait")),
        Network("ewb", "EWB",
            setOf(2241L),
            setOf("ewb")),
        Network("eo-charging", "EO Charging",
            setOf(3298L),
            setOf("eocharging")),
        Network("ewp-energie-und-wasser-potsdam-gmbh", "EWP : Energie und Wasser Potsdam GmbH",
            setOf(3325L),
            setOf("ewpenergieundwasserpotsdam")),
        Network("electrico-es", "Electrico.es",
            setOf(3704L),
            setOf("electricoes")),
        Network("circle-k", "Circle K",
            setOf(3510L),
            setOf("circlek")),
        Network("lsw-energie", "LSW Energie",
            setOf(128L),
            setOf("lswenergie")),
        Network("zest-charging", "Zest Charging",
            setOf(3581L),
            setOf("zestcharging")),
        Network("ev-point", "EV-Point",
            setOf(49L),
            setOf("evpoint")),
        Network("plug-n-roll", "Plug n Roll",
            setOf(3280L),
            setOf("plugnroll")),
        Network("mainova", "Mainova",
            setOf(165L),
            setOf("mainova")),
        Network("stadtwerke-gottingen", "Stadtwerke Göttingen",
            setOf(132L),
            setOf("stadtwerkegottingen")),
        Network("oeste-movilidad-es", "OESTE Movilidad",
            setOf(3608L),
            setOf("oestemovilidades")),
        Network("esb-ecars", "ESB Ecars",
            setOf(22L),
            setOf("esbecars")),
        Network("electrip", "Electrip",
            setOf(3823L),
            setOf("electrip")),
        Network("ekomobil", "Ekomobil",
            setOf(3342L),
            setOf("ekomobil")),
        Network("edf", "EDF",
            setOf(3312L),
            setOf("edf")),
        Network("becharged", "BeCharged",
            setOf(94L),
            setOf("becharged")),
        Network("porsche-smart-mobility-gmbh", "Porsche Smart Mobility GmbH",
            setOf(3523L),
            setOf("porschesmartmobility")),
        Network("evyve", "evyve",
            setOf(3587L),
            setOf("evyve")),
        Network("vend-electric", "Vend Electric",
            setOf(3473L),
            setOf("vendelectric")),
        Network("aral-pulse", "Aral pulse",
            setOf(3455L),
            setOf("aralpulse")),
        Network("e-totem", "e-totem",
            setOf(55L),
            setOf("etotem")),
        Network("ouest-charge", "Ouest Charge",
            setOf(3640L),
            setOf("ouestcharge")),
        Network("scottish-power", "Scottish Power",
            setOf(3537L),
            setOf("scottishpower")),
        Network("plug-n-go-ltd", "Plug N Go Ltd",
            setOf(3613L),
            setOf("plugngo")),
        Network("flowbird-uk", "Flowbird",
            setOf(3739L),
            setOf("flowbirduk")),
        Network("stations-e", "Stations-e",
            setOf(3485L),
            setOf("stationse")),
        Network("smart-charge-by-sainsbury-s-uk", "Smart Charge by Sainsbury's",
            setOf(3747L),
            setOf("smartchargebysainsburysuk")),
        Network("project-ev", "Project EV",
            setOf(3629L),
            setOf("projectev")),
        Network("ewr-gmbh-e-mobile", "EWR gmbh e-mobile",
            setOf(109L),
            setOf("ewremobile")),
        Network("biggie-energie", "BIGGIE Energie",
            setOf(3443L),
            setOf("biggieenergie")),
        Network("e-charge50-fr", "E-Charge50",
            setOf(3755L),
            setOf("echarge50fr")),
        Network("pogo-charge-gb", "Pogo Charge",
            setOf(3769L),
            setOf("pogochargegb")),
        Network("vlotte", "Vlotte",
            setOf(99L),
            setOf("vlotte")),
        Network("stadtwerke-strahlsund", "Stadtwerke Strahlsund",
            setOf(153L),
            setOf("stadtwerkestrahlsund")),
        Network("optimile", "Optimile",
            setOf(3590L),
            setOf("optimile")),
        Network("q1-autostrom", "Q1 Autostrom",
            setOf(3429L),
            setOf("q1autostrom")),
        Network("osterholzer-stadtwerke", "Osterholzer Stadtwerke",
            setOf(124L),
            setOf("osterholzerstadtwerke")),
        Network("enewa", "ENEWA",
            setOf(172L),
            setOf("enewa")),
        Network("chargeguru", "ChargeGuru",
            setOf(3816L),
            setOf("chargeguru")),
        Network("interparking-es", "Interparking",
            setOf(3975L),
            setOf("interparkinges")),
        Network("emallorca-es", "eMallorca",
            setOf(3671L),
            setOf("emallorcaes")),
        Network("r3", "R3",
            setOf(3484L),
            setOf("r3")),
        Network("eways", "eways",
            setOf(3444L),
            setOf("eways")),
        Network("elli-volkswagen-group-charging-gmbh", "Elli (Volkswagen Group Charging GmbH)",
            setOf(3437L),
            setOf("ellivolkswagengroupcharging")),
        Network("stadtwerke-rostock", "Stadtwerke Rostock",
            setOf(154L),
            setOf("stadtwerkerostock")),
        Network("total-be-plugtodrive", "TOTAL Be PlugToDrive",
            setOf(175L),
            setOf("totalbeplugtodrive")),
        Network("nomadpower", "Nomadpower",
            setOf(196L),
            setOf("nomadpower")),
        Network("stadtische-werke-magdeburg", "Städtische Werke Magdeburg",
            setOf(152L),
            setOf("stadtischewerkemagdeburg")),
        Network("stadtwerke-halle", "Stadtwerke Halle",
            setOf(161L),
            setOf("stadtwerkehalle")),
        Network("stadtwerke-wittenberg", "Stadtwerke Wittenberg",
            setOf(159L),
            setOf("stadtwerkewittenberg")),
        Network("ballenoil-es", "Ballenoil",
            setOf(3880L),
            setOf("ballenoiles")),
        Network("digavel-es", "Digavel",
            setOf(3572L),
            setOf("digaveles")),
        Network("ev-dot", "EV Dot",
            setOf(3446L),
            setOf("evdot")),
        Network("bluetorino", "BLUETORINO",
            setOf(3331L),
            setOf("bluetorino")),
        Network("e-laad", "e-Laad",
            setOf(29L),
            setOf("elaad")),
        Network("drive-eco", "Drive Eco",
            setOf(3316L),
            setOf("driveeco")),
        Network("e-flux", "E-Flux",
            setOf(3579L),
            setOf("eflux")),
        Network("l-electra-es", "L'electra",
            setOf(3770L),
            setOf("lelectraes")),
        Network("evzen-fr", "EVzen",
            setOf(3641L),
            setOf("evzenfr")),
        Network("gardauno", "GardaUno",
            setOf(204L),
            setOf("gardauno")),
        Network("total-nl-plugtodrive", "TOTAL Nl PlugToDrive",
            setOf(174L),
            setOf("totalnlplugtodrive")),
        Network("kelag-ag", "Kelag AG",
            setOf(3285L),
            setOf("kelag")),
        Network("ores", "ORES",
            setOf(1236L),
            setOf("ores")),
        Network("easy4you", "Easy4You",
            setOf(3314L),
            setOf("easy4you")),
        Network("be-emobil", "be emobil",
            setOf(214L),
            setOf("beemobil")),
        Network("vilalta-greenergy-es", "Vilalta Greenergy",
            setOf(3785L),
            setOf("vilaltagreenergyes")),
        Network("electro-emt", "Electro-EMT",
            setOf(3553L),
            setOf("electroemt")),
        Network("ferrovial-es", "Ferrovial",
            setOf(3772L),
            setOf("ferroviales")),
        Network("renault", "Renault",
            setOf(3275L),
            setOf("renault")),
        Network("sigeif-fr", "Sigeif",
            setOf(3512L),
            setOf("sigeiffr")),
        Network("applegreen-fast-charge", "Applegreen Fast Charge",
            setOf(3516L),
            setOf("applegreenfastcharge")),
        Network("enovates", "eNovates",
            setOf(181L),
            setOf("enovates")),
        Network("stadtwerke-haldensleben-swh", "Stadtwerke Haldensleben  SWH",
            setOf(148L),
            setOf("stadtwerkehaldenslebenswh")),
        Network("crece-energia-es", "Crece Energia",
            setOf(3954L),
            setOf("creceenergiaes")),
        Network("pavapark-es", "Pavapark",
            setOf(3955L),
            setOf("pavaparkes")),
        Network("arnold-clark-dealer-network-uk", "Arnold Clark Dealer Network",
            setOf(3842L),
            setOf("arnoldclarkdealernetworkuk")),
        Network("aae", "AAE",
            setOf(3333L),
            setOf("aae")),
        Network("avia-fr", "Avia",
            setOf(3652L),
            setOf("aviafr")),
        Network("kaufland-echarge", "Kaufland eCharge",
            setOf(3714L),
            setOf("kauflandecharge")),
        Network("stadtwerke-elmshorn", "Stadtwerke Elmshorn",
            setOf(170L),
            setOf("stadtwerkeelmshorn")),
        Network("ggew", "GGEW",
            setOf(163L),
            setOf("ggew")),
        Network("b-sm-es", "B:SM",
            setOf(3577L),
            setOf("bsmes")),
        Network("zen-zero-emission-network-proviridis", "ZEN (Zero Emission Network)/PROVIRIDIS",
            setOf(3448L),
            setOf("zenzeroemissionnetworkproviridis")),
        Network("bmm-energy-uk", "BMM Energy",
            setOf(3946L),
            setOf("bmmenergyuk")),
        Network("drax-energy-solutions-limited", "Drax Energy Solutions Limited",
            setOf(3614L),
            setOf("draxenergysolutionslimited")),
        Network("flow-charging", "FLOW Charging",
            setOf(197L),
            setOf("flowcharging")),
        Network("ella", "Ella",
            setOf(3287L),
            setOf("ella")),
        Network("mobib-belgium", "Mobib (Belgium)",
            setOf(79L),
            setOf("mobibbelgium")),
        Network("ecarup-ch", "eCarUp",
            setOf(3891L),
            setOf("ecarupch")),
        Network("stadtwerke-rinteln", "Stadtwerke Rinteln",
            setOf(143L),
            setOf("stadtwerkerinteln")),
        Network("evl-de", "EVL (de)",
            setOf(3351L),
            setOf("evlde")),
        Network("evology-parking", "Evology Parking",
            setOf(3759L),
            setOf("evologyparking")),
        Network("dragon-charging", "Dragon Charging",
            setOf(3496L),
            setOf("dragoncharging")),
        Network("spotlink-e-motion", "SpotLink – e.motion",
            setOf(3329L),
            setOf("spotlinkemotion")),
        Network("enerhub", "Enerhub",
            setOf(3370L),
            setOf("enerhub")),
        Network("green-land-mobility-italy", "Green Land Mobility (Italy)",
            setOf(84L),
            setOf("greenlandmobilityitaly")),
        Network("evcore-se", "EVcore",
            setOf(3764L),
            setOf("evcore")),
        Network("blink-charging", "Blink Charging",
            setOf(9L, 3737L),
            setOf("blinkcharging", "blinkcharginguk")),
        Network("reev-de", "Reev",
            setOf(3582L),
            setOf("reevde")),
        Network("burgerladenetz-de", "BürgerLadenetz",
            setOf(3796L),
            setOf("burgerladenetzde")),
        Network("harz-energie", "Harz Energie",
            setOf(122L),
            setOf("harzenergie")),
        Network("gai-charge", "Gai Charge",
            setOf(3790L),
            setOf("gaicharge")),
        Network("uenergia-es", "UEnergia",
            setOf(3947L),
            setOf("uenergiaes")),
        Network("forev", "ForEV",
            setOf(3845L),
            setOf("forev")),
        Network("tap-electric", "Tap Electric",
            setOf(3884L),
            setOf("tapelectric")),
        Network("nrg4you", "NRG4YOU",
            setOf(3438L),
            setOf("nrg4you")),
        Network("eneco", "Eneco",
            setOf(3394L),
            setOf("eneco")),
        Network("zencar", "ZenCar",
            setOf(100L),
            setOf("zencar")),
        Network("stadtwerke-munster", "Stadtwerke Münster",
            setOf(225L),
            setOf("stadtwerkemunster")),
        Network("badenova-de", "Badenova",
            setOf(3292L),
            setOf("badenovade")),
        Network("chargecloud-de", "Chargecloud",
            setOf(3758L),
            setOf("chargecloudde")),
        Network("next-step-mobility-de", "Next Step Mobility",
            setOf(3466L),
            setOf("nextstepmobilityde")),
        Network("orlencharge", "Orlencharge",
            setOf(3396L),
            setOf("orlencharge")),
        Network("stadtwerke-wernigerode", "Stadtwerke Wernigerode",
            setOf(130L),
            setOf("stadtwerkewernigerode")),
        Network("dream-energy", "Dream Energy",
            setOf(3651L),
            setOf("dreamenergy")),
        Network("axpo-energy-solutions-italia", "Axpo Energy Solutions Italia",
            setOf(3352L),
            setOf("axpoenergysolutionsitalia")),
        Network("mistergreen-the-fast-charger-network", "MisterGreen, The Fast Charger Network",
            setOf(112L),
            setOf("mistergreenthefastchargernetwork")),
        Network("chargenode-se", "ChargeNode",
            setOf(3765L),
            setOf("chargenode")),
        Network("okq8-se", "OKQ8",
            setOf(3763L),
            setOf("okq8")),
        Network("enercharge", "Enercharge",
            setOf(3405L),
            setOf("enercharge")),
        Network("powerland-be", "Powerland",
            setOf(3844L),
            setOf("powerlandbe")),
        Network("mobilityplus", "MobilityPlus",
            setOf(3808L),
            setOf("mobilityplus")),
        Network("smappee", "Smappee",
            setOf(3754L),
            setOf("smappee")),
        Network("power-station-be", "Power Station",
            setOf(114L),
            setOf("powerstationbe")),
        Network("electric-driving-colruytgroup-com", "electric-driving.colruytgroup.com",
            setOf(232L),
            setOf("electricdrivingcolruytgroupcom")),
        Network("vitaemobility", "Vitaemobility",
            setOf(61L),
            setOf("vitaemobility")),
        Network("ev24", "EV24",
            setOf(3898L),
            setOf("ev24")),
        Network("justplugin-nl", "Justplugin",
            setOf(3746L),
            setOf("justpluginnl")),
        Network("jet-charge-uk", "Jet Charge",
            setOf(3752L),
            setOf("jetchargeuk")),
        Network("chargeit-mobility", "ChargeIT mobility",
            setOf(101L),
            setOf("chargeitmobility")),
        Network("stadtwerke-wolfenbuttel", "Stadtwerke Wolfenbüttel",
            setOf(166L),
            setOf("stadtwerkewolfenbuttel")),
        Network("stadtwerke-grevesmuhlen", "Stadtwerke Grevesmühlen",
            setOf(151L),
            setOf("stadtwerkegrevesmuhlen")),
        Network("estabanell-energia", "Estabanell Energia",
            setOf(209L),
            setOf("estabanellenergia")),
        Network("yawatt-es", "Yawatt (Es)",
            setOf(3589L),
            setOf("yawattes")),
        Network("g2mobility", "G2mobility",
            setOf(116L),
            setOf("g2mobility")),
        Network("belib", "Belib’",
            setOf(1235L),
            setOf("belib")),
        Network("ecocharge77", "EcoCharge77",
            setOf(3413L),
            setOf("ecocharge77")),
        Network("plug-charging", "Plug Charging",
            setOf(3667L),
            setOf("plugcharging")),
        Network("epower", "ePower",
            setOf(3449L),
            setOf("epower")),
        Network("eb-charging", "EB Charging",
            setOf(3391L),
            setOf("ebcharging")),
        Network("alfapower-uk", "Alfapower",
            setOf(3326L),
            setOf("alfapoweruk")),
        Network("citipark-uk", "CitiPark",
            setOf(3670L),
            setOf("citiparkuk")),
        Network("eviso", "eVISO",
            setOf(3472L),
            setOf("eviso")),
        Network("ecospazio-italy", "Ecospazio (Italy)",
            setOf(83L),
            setOf("ecospazioitaly")),
        Network("kople", "Kople",
            setOf(3536L),
            setOf("kople")),
        Network("lad-opp", "Lad Opp",
            setOf(3541L),
            setOf("ladopp")),
        Network("jolt", "Jolt",
            setOf(3529L),
            setOf("jolt")),
        Network("salzburg-ag", "Salzburg AG",
            setOf(3713L),
            setOf("salzburg")),
        Network("greems-il", "Greems",
            setOf(3899L),
            setOf("greemsil")),
        Network("park-charge-ch", "Park & Charge",
            setOf(97L),
            setOf("parkchargech")),
        Network("citywatt-de", "Citywatt",
            setOf(3892L),
            setOf("citywattde")),
        Network("rwe-mobility-essent", "RWE Mobility/Essent",
            setOf(48L),
            setOf("rwemobilityessent")),
        Network("werraenergie", "Werraenergie",
            setOf(195L),
            setOf("werraenergie")),
        Network("evs-energieversorgung-sylt", "EVS Energieversorgung Sylt",
            setOf(137L),
            setOf("evsenergieversorgungsylt")),
        Network("zeag-energie", "ZEAG Energie",
            setOf(176L),
            setOf("zeagenergie")),
        Network("petite-borne-fr", "Petite Borne",
            setOf(3999L),
            setOf("petitebornefr")),
        Network("reveo-fr", "Révéo",
            setOf(3257L),
            setOf("reveofr")),
        Network("sdey-fr", "SDEY (Fr)",
            setOf(33L),
            setOf("sdeyfr")),
        Network("source-gb", "Source",
            setOf(3797L),
            setOf("sourcegb")),
        Network("zero-carbon-world", "Zero Carbon World",
            setOf(19L),
            setOf("zerocarbonworld")),
        Network("eg-group-ev-point-uk", "EG Group EV Point",
            setOf(3599L),
            setOf("eggroupevpointuk")),
        Network("smart-charge-au", "Smart Charge",
            setOf(3658L),
            setOf("smartchargeau")),
        Network("apcoa-parking", "APCOA Parking",
            setOf(3637L),
            setOf("apcoaparking")),
        Network("flyelectric-it", "Flyelectric",
            setOf(3841L),
            setOf("flyelectricit")),
        Network("everse", "EVerse",
            setOf(3535L),
            setOf("everse")),
        Network("saiel-it", "Saiel",
            setOf(3521L),
            setOf("saielit")),
        Network("time-park-no", "Time Park",
            setOf(3859L),
            setOf("timeparkno")),

        // --- Bnetza-only operators (>=50 stations, no OCM id), matched by
        // free-text Betreiber keyword; see GitHub issue #31. ---
        Network("wirelane-public-1", "Wirelane Public 1",
            setOf(),
            setOf("wirelane public 1")),
        Network("servipark-deutschland", "Servipark Deutschland",
            setOf(),
            setOf("servipark deutschland")),
        Network("tanke", "TankE",
            setOf(),
            setOf("tanke")),
        Network("eze-network", "eze.network",
            setOf(),
            setOf("eze.network")),
        Network("robert-bosch", "Robert Bosch",
            setOf(),
            setOf("robert bosch")),
        Network("berliner-stadtwerke-kommunalpartner", "Berliner Stadtwerke KommunalPartner",
            setOf(),
            setOf("berliner stadtwerke kommunalpartner")),
        Network("audi", "Audi",
            setOf(),
            setOf("audi")),
        Network("swm-versorgungs", "SWM Versorgungs",
            setOf(),
            setOf("swm versorgungs")),
        Network("wattif-europe", "Wattif Europe",
            setOf(),
            setOf("wattif europe")),
        Network("stadtwerke-stuttgart", "Stadtwerke Stuttgart",
            setOf(),
            setOf("stadtwerke stuttgart")),
        Network("teag-mobil", "TEAG Mobil",
            setOf(),
            setOf("teag mobil")),
        Network("deer", "deer",
            setOf(),
            setOf("deer")),
        Network("eswe-versorgungs", "ESWE Versorgungs",
            setOf(),
            setOf("eswe versorgungs")),
        Network("westfalen-weser-ladeservice", "Westfalen Weser Ladeservice",
            setOf(),
            setOf("westfalen weser ladeservice")),
        Network("gp-joule-connect", "GP Joule Connect",
            setOf(),
            setOf("gp joule connect")),
        Network("rewag", "REWAG",
            setOf(),
            setOf("rewag")),
        Network("cubos-service", "CUBOS Service",
            setOf(),
            setOf("cubos service")),
        Network("kaufland-dienstleistung", "Kaufland Dienstleistung",
            setOf(),
            setOf("kaufland dienstleistung")),
        Network("regioladen", "Regioladen",
            setOf(),
            setOf("regioladen")),
        Network("georg-jos-kaes", "Georg Jos. Kaes",
            setOf(),
            setOf("georg jos. kaes")),
        Network("stadtwerke-leipzig", "Stadtwerke Leipzig",
            setOf(),
            setOf("stadtwerke leipzig")),
        Network("hochtief-ladepartner", "HOCHTIEF Ladepartner",
            setOf(),
            setOf("hochtief ladepartner")),
        Network("fraunhofer-gesellschaft", "Fraunhofer-Gesellschaft",
            setOf(),
            setOf("fraunhofer-gesellschaft")),
        Network("stawag-stadt-und-stadteregionswerke-aachen", "STAWAG - Stadt- und Städteregionswerke Aachen",
            setOf(),
            setOf("stawag - stadt- und stadteregionswerke aachen")),
        Network("q-park-recharge-germany", "Q-Park Recharge Germany",
            setOf(),
            setOf("q-park recharge germany")),
        Network("home-of-mobility", "HomE of Mobility",
            setOf(),
            setOf("home of mobility")),
        Network("edeka-miha-charge", "EDEKA-MIHA Charge",
            setOf(),
            setOf("edeka-miha charge")),
        Network("apcoa-deutschland", "APCOA Deutschland",
            setOf(),
            setOf("apcoa deutschland")),
        Network("getec-mobility-solutions", "GETEC mobility solutions",
            setOf(),
            setOf("getec mobility solutions")),
        Network("parkraumgesellschaft-baden-wurttemberg", "Parkraumgesellschaft Baden-Württemberg",
            setOf(),
            setOf("parkraumgesellschaft baden-wurttemberg")),
        Network("volkswagen-ag-werk-wolfsburg", "Volkswagen AG - Werk Wolfsburg",
            setOf(),
            setOf("volkswagen ag - werk wolfsburg")),
        Network("zweckverband-region-schwabische-alb", "Zweckverband Region Schwäbische Alb",
            setOf(),
            setOf("zweckverband region schwabische alb")),
        Network("stadtwerke-duisburg", "Stadtwerke Duisburg",
            setOf(),
            setOf("stadtwerke duisburg")),
        Network("lew-natur", "LEW Natur",
            setOf(),
            setOf("lew natur")),
        Network("gls-mobility", "GLS Mobility",
            setOf(),
            setOf("gls mobility")),
        Network("amperio", "amperio",
            setOf(),
            setOf("amperio")),
        Network("stadtwerke-bochum", "Stadtwerke Bochum",
            setOf(),
            setOf("stadtwerke bochum")),
        Network("viocon", "VIOCON",
            setOf(),
            setOf("viocon")),
        Network("aldi-nord-deutschland-stiftung", "ALDI Nord Deutschland Stiftung",
            setOf(),
            setOf("aldi nord deutschland stiftung")),
        Network("bilkraft", "Bilkraft",
            setOf(),
            setOf("bilkraft")),
        Network("ecowerk-e-charge", "ecowerk e-charge",
            setOf(),
            setOf("ecowerk e-charge")),
        Network("osnabrucker-parkstatten-betriebsgesellschaft", "Osnabrücker Parkstätten-Betriebsgesellschaft",
            setOf(),
            setOf("osnabrucker parkstatten-betriebsgesellschaft")),
        Network("backcharge", "Backcharge",
            setOf(),
            setOf("backcharge")),
        Network("inno2grid", "inno2grid",
            setOf(),
            setOf("inno2grid")),
        Network("stadtwerke-wurzburg", "Stadtwerke Würzburg",
            setOf(),
            setOf("stadtwerke wurzburg")),
        Network("wirelane", "Wirelane",
            setOf(),
            setOf("wirelane")),
        Network("flughafen-munchen", "Flughafen München",
            setOf(),
            setOf("flughafen munchen")),
        Network("infra-furth-service", "infra fürth service",
            setOf(),
            setOf("infra furth service")),
        Network("swlb-mobilitat", "SWLB Mobilität",
            setOf(),
            setOf("swlb mobilitat")),
        Network("westfalen", "Westfalen",
            setOf(),
            setOf("westfalen")),
        Network("ladestationen-sudwest", "Ladestationen Südwest",
            setOf(),
            setOf("ladestationen sudwest")),
        Network("fraport", "Fraport",
            setOf(),
            setOf("fraport")),
        Network("e-con", "e-con",
            setOf(),
            setOf("e-con")),
        Network("nonoxx-pro", "nonoxx pro",
            setOf(),
            setOf("nonoxx pro")),
        Network("oms-prufservice", "OMS Prüfservice",
            setOf(),
            setOf("oms prufservice")),
        Network("brepark", "BREPARK",
            setOf(),
            setOf("brepark")),
        Network("oberhessische-versorgungsbetriebe", "Oberhessische Versorgungsbetriebe",
            setOf(),
            setOf("oberhessische versorgungsbetriebe")),
        Network("volkswagen-ag-werk-hannover", "Volkswagen AG, Werk Hannover",
            setOf(),
            setOf("volkswagen ag, werk hannover")),
        Network("stadtwerke-heilbronn", "Stadtwerke Heilbronn",
            setOf(),
            setOf("stadtwerke heilbronn")),
        Network("adolf-wurth", "Adolf Würth",
            setOf(),
            setOf("adolf wurth")),
        Network("mark-e-aktiengesellschaft", "Mark-E Aktiengesellschaft",
            setOf(),
            setOf("mark-e aktiengesellschaft")),
        Network("pluq-assets-bv", "Pluq Assets BV",
            setOf(),
            setOf("pluq assets bv")),
        Network("cocharge", "cocharge",
            setOf(),
            setOf("cocharge")),
        Network("albwerk-elektro-und-kommunikationstechnik", "Albwerk Elektro- und Kommunikationstechnik",
            setOf(),
            setOf("albwerk elektro- und kommunikationstechnik")),
        Network("avacon", "Avacon",
            setOf(),
            setOf("avacon")),
        Network("reload-solution", "Reload-Solution",
            setOf(),
            setOf("reload-solution")),
        Network("stadtwerke-konstanz-mobil", "Stadtwerke Konstanz Mobil",
            setOf(),
            setOf("stadtwerke konstanz mobil")),
        Network("autostrom-plus", "Autostrom plus",
            setOf(),
            setOf("autostrom plus")),
        Network("si-energy", "SI Energy",
            setOf(),
            setOf("si energy")),
        Network("wemag", "WEMAG",
            setOf(),
            setOf("wemag")),
        Network("areacharge", "AreaCharge",
            setOf(),
            setOf("areacharge")),
        Network("cut-energy", "Cut! Energy",
            setOf(),
            setOf("cut! energy")),
        Network("stadtwerke-bamberg-verkehrs-und-park", "Stadtwerke Bamberg Verkehrs- und Park",
            setOf(),
            setOf("stadtwerke bamberg verkehrs- und park")),
        Network("suwag-vertrieb", "Süwag Vertrieb",
            setOf(),
            setOf("suwag vertrieb")),
        Network("uz-mainfranken-eg", "ÜZ Mainfranken eG",
            setOf(),
            setOf("uz mainfranken eg")),
        Network("stadtwerke-kiel", "Stadtwerke Kiel",
            setOf(),
            setOf("stadtwerke kiel")),
        Network("swp-stadtwerke-pforzheim", "SWP Stadtwerke Pforzheim",
            setOf(),
            setOf("swp stadtwerke pforzheim")),
        Network("goldbeck-parking-services", "GOLDBECK Parking Services",
            setOf(),
            setOf("goldbeck parking services")),
        Network("gruppen-gas-und-elektrizitatswerk-bergstrasse", "Gruppen-Gas- und Elektrizitätswerk Bergstraße",
            setOf(),
            setOf("gruppen-gas- und elektrizitatswerk bergstrasse")),
        Network("stadtwerke-bielefeld", "Stadtwerke Bielefeld",
            setOf(),
            setOf("stadtwerke bielefeld")),
        Network("haller-mobilitat-und-warme", "Haller Mobilität und Wärme",
            setOf(),
            setOf("haller mobilitat und warme")),
        Network("e-regio", "e-regio",
            setOf(),
            setOf("e-regio")),
        Network("jet-tankstellen-deutschland", "JET Tankstellen Deutschland",
            setOf(),
            setOf("jet tankstellen deutschland")),
        Network("stadtwerke-sh", "Stadtwerke SH",
            setOf(),
            setOf("stadtwerke sh")),
        Network("mainzer-stadtwerke", "Mainzer Stadtwerke",
            setOf(),
            setOf("mainzer stadtwerke")),
        Network("nurnbergmesse", "NürnbergMesse",
            setOf(),
            setOf("nurnbergmesse")),
        Network("stadtwerke-husum", "Stadtwerke Husum",
            setOf(),
            setOf("stadtwerke husum")),
        Network("stadtwerke-russelsheim", "Stadtwerke Rüsselsheim",
            setOf(),
            setOf("stadtwerke russelsheim")),
        Network("erneuerbare-fur-marburg-biedenkopf", "Erneuerbare für Marburg-Biedenkopf",
            setOf(),
            setOf("erneuerbare fur marburg-biedenkopf")),
        Network("ikea-deutschland", "IKEA Deutschland",
            setOf(),
            setOf("ikea deutschland")),
        Network("autohaus-bernds", "Autohaus Bernds",
            setOf(),
            setOf("autohaus bernds")),
        Network("stadtwerke-iserlohn", "Stadtwerke Iserlohn",
            setOf(),
            setOf("stadtwerke iserlohn")),
        Network("stadtwerke-solingen", "Stadtwerke Solingen",
            setOf(),
            setOf("stadtwerke solingen")),
        Network("eulektro", "Eulektro",
            setOf(),
            setOf("eulektro")),
        Network("elektrizitatswerk-mittelbaden", "Elektrizitätswerk Mittelbaden",
            setOf(),
            setOf("elektrizitatswerk mittelbaden")),
        Network("volkswagen-ag-standort-braunschweig", "Volkswagen AG, Standort Braunschweig",
            setOf(),
            setOf("volkswagen ag, standort braunschweig")),
        Network("aachener-parkhaus", "Aachener Parkhaus",
            setOf(),
            setOf("aachener parkhaus")),
        Network("flughafen-stuttgart", "Flughafen Stuttgart",
            setOf(),
            setOf("flughafen stuttgart")),
        Network("stadtwerke-castrop-rauxel", "Stadtwerke Castrop-Rauxel",
            setOf(),
            setOf("stadtwerke castrop-rauxel")),
        Network("stadtwerke-duren", "Stadtwerke Düren",
            setOf(),
            setOf("stadtwerke duren")),
        Network("chargeforce", "Chargeforce",
            setOf(),
            setOf("chargeforce")),
        Network("stromspeichermarkt", "StromSpeicherMarkt",
            setOf(),
            setOf("stromspeichermarkt")),
        Network("baywa-mobility-solutions", "BayWa Mobility Solutions",
            setOf(),
            setOf("baywa mobility solutions")),
        Network("em1", "EM1",
            setOf(),
            setOf("em1")),
        Network("allgauer-uberlandwerk", "Allgäuer Überlandwerk",
            setOf(),
            setOf("allgauer uberlandwerk")),
        Network("eg-elektromobilitat", "EG Elektromobilität",
            setOf(),
            setOf("eg elektromobilitat")),
        Network("swarco-traffic-systems", "Swarco Traffic Systems",
            setOf(),
            setOf("swarco traffic systems")),
        Network("volkswagen-sachsen-gmbh-werk-zwickau", "Volkswagen Sachsen GmbH, Werk Zwickau",
            setOf(),
            setOf("volkswagen sachsen gmbh, werk zwickau")),
        Network("orange-charging-b-v", "Orange Charging B.V",
            setOf(),
            setOf("orange charging b.v")),
        Network("suc", "SÜC",
            setOf(),
            setOf("suc")),
        Network("swb-vertrieb-bremen", "swb Vertrieb Bremen",
            setOf(),
            setOf("swb vertrieb bremen")),
        Network("ewr", "EWR",
            setOf(),
            setOf("ewr")),
        Network("energis", "energis",
            setOf(),
            setOf("energis")),
        Network("leitungstiefbau-dithmarschen", "Leitungstiefbau Dithmarschen",
            setOf(),
            setOf("leitungstiefbau dithmarschen")),
        Network("volkswagen-ag-zweigniederlassung-werk-kassel", "Volkswagen AG, Zweigniederlassung Werk Kassel",
            setOf(),
            setOf("volkswagen ag, zweigniederlassung werk kassel")),
        Network("swn-stadtwerke-neumunster", "SWN Stadtwerke Neumünster",
            setOf(),
            setOf("swn stadtwerke neumunster")),
        Network("abfallwirtschaft-und-stadtreinigung-freiburg", "Abfallwirtschaft und Stadtreinigung Freiburg",
            setOf(),
            setOf("abfallwirtschaft und stadtreinigung freiburg")),
        Network("amba-operations", "amba operations",
            setOf(),
            setOf("amba operations")),
        Network("edeka-nw-stiftung", "EDEKA NW Stiftung",
            setOf(),
            setOf("edeka nw stiftung")),
        Network("nvb-smart", "nvb smart",
            setOf(),
            setOf("nvb smart")),
        Network("stadtwerke-stendal", "Stadtwerke Stendal",
            setOf(),
            setOf("stadtwerke stendal")),
        Network("union-investment-real-estate-digital", "Union Investment Real Estate Digital",
            setOf(),
            setOf("union investment real estate digital")),
        Network("universitatsklinikum-heidelberg-anstalt-offentlichen-rechts", "Universitätsklinikum Heidelberg Anstalt öffentlichen Rechts",
            setOf(),
            setOf("universitatsklinikum heidelberg anstalt offentlichen rechts")),
        Network("volkswagen-ag-werk-salzgitter", "Volkswagen AG, Werk Salzgitter",
            setOf(),
            setOf("volkswagen ag, werk salzgitter")),
        Network("gfc", "GFC",
            setOf(),
            setOf("gfc")),
        Network("ladesonne", "Ladesonne",
            setOf(),
            setOf("ladesonne")),
        Network("scharr-warme", "SCHARR WÄRME",
            setOf(),
            setOf("scharr warme")),
        Network("stadtverwaltung-schwabisch-gmund", "Stadtverwaltung Schwäbisch Gmünd",
            setOf(),
            setOf("stadtverwaltung schwabisch gmund")),
        Network("tank-rast-entwicklungsgesellschaft", "Tank & Rast Entwicklungsgesellschaft",
            setOf(),
            setOf("tank & rast entwicklungsgesellschaft")),
        Network("charge-construct", "Charge Construct",
            setOf(),
            setOf("charge construct")),
        Network("pariamus", "Pariamus",
            setOf(),
            setOf("pariamus")),
        Network("capgemini-deutschland", "Capgemini Deutschland",
            setOf(),
            setOf("capgemini deutschland")),
        Network("daimler-truck", "Daimler Truck",
            setOf(),
            setOf("daimler truck")),
        Network("go2zero-charging-solutions", "go2zero charging solutions",
            setOf(),
            setOf("go2zero charging solutions")),
        Network("mwenergy", "mwenergy",
            setOf(),
            setOf("mwenergy")),
        Network("stadtwerke-gronau", "Stadtwerke Gronau",
            setOf(),
            setOf("stadtwerke gronau")),
        Network("chargemaker", "Chargemaker",
            setOf(),
            setOf("chargemaker")),
        Network("esel-cab", "ESEL.CAB",
            setOf(),
            setOf("esel.cab")),
        Network("hahn-automobile", "Hahn Automobile",
            setOf(),
            setOf("hahn automobile")),
        Network("edeka-sudbayern-handels-stiftung", "EDEKA Südbayern Handels Stiftung",
            setOf(),
            setOf("edeka sudbayern handels stiftung")),
        Network("evry-operations", "Evry Operations",
            setOf(),
            setOf("evry operations")),
        Network("b-b-parkhaus", "B+B Parkhaus",
            setOf(),
            setOf("b+b parkhaus")),
        Network("stadtwerke-hamm", "Stadtwerke Hamm",
            setOf(),
            setOf("stadtwerke hamm")),
        Network("volkswagen-immobilien", "Volkswagen Immobilien",
            setOf(),
            setOf("volkswagen immobilien")),
        Network("bidirex", "Bidirex",
            setOf(),
            setOf("bidirex")),
        Network("opa-verkehrsgesellschaft", "öPA Verkehrsgesellschaft",
            setOf(),
            setOf("opa verkehrsgesellschaft")),
        Network("harpen-immobilien", "Harpen Immobilien",
            setOf(),
            setOf("harpen immobilien")),
        Network("ifg-ingolstadt-aor", "IFG Ingolstadt AöR",
            setOf(),
            setOf("ifg ingolstadt aor")),
        Network("mblty", "mblty",
            setOf(),
            setOf("mblty")),
        Network("orlen-deutschland", "ORLEN Deutschland",
            setOf(),
            setOf("orlen deutschland")),
        Network("vereinigte-stadtwerke", "Vereinigte Stadtwerke",
            setOf(),
            setOf("vereinigte stadtwerke")),
        Network("verkehrsbetriebe-speyer", "Verkehrsbetriebe Speyer",
            setOf(),
            setOf("verkehrsbetriebe speyer")),
        Network("dayser-deutschland", "Dayser Deutschland",
            setOf(),
            setOf("dayser deutschland")),
        Network("inselwerke-eg", "Inselwerke eG",
            setOf(),
            setOf("inselwerke eg")),
        Network("parkgaragengesellschaft-baden-baden", "Parkgaragengesellschaft Baden-Baden",
            setOf(),
            setOf("parkgaragengesellschaft baden-baden")),
        Network("vwew-kommunal", "VWEW Kommunal",
            setOf(),
            setOf("vwew kommunal")),
        Network("netto-marken-discount-stiftung", "Netto Marken-Discount Stiftung",
            setOf(),
            setOf("netto marken-discount stiftung")),
        Network("stadtwerke-neumarkt-i-d-opf-freizeit-leben-ku", "Stadtwerke Neumarkt i.d.OPf. Freizeit & Leben KU",
            setOf(),
            setOf("stadtwerke neumarkt i.d.opf. freizeit & leben ku")),
        Network("e-dis", "E.DIS",
            setOf(),
            setOf("e.dis")),
        Network("flughafen-koln-bonn", "Flughafen Köln/Bonn",
            setOf(),
            setOf("flughafen koln/bonn")),
        Network("on-charge", "On Charge",
            setOf(),
            setOf("on charge")),
        Network("stadtwerke-lingen", "Stadtwerke Lingen",
            setOf(),
            setOf("stadtwerke lingen")),
    )

    private val byKeyMap: Map<String, Network> = all.associateBy { it.key }
    private val byOperatorId: Map<Long, Network> =
        all.flatMap { n -> n.operatorIds.map { it to n } }.toMap()

    fun byKey(key: String): Network? = byKeyMap[key]

    /**
     * Keys this catalog used to give a network, mapped to the current one.
     * A stored selection is read through [currentKey]: a key that no longer
     * names anything is silently dropped from the picker, so renaming one
     * without this would take the network out of every install that had it
     * ticked.
     */
    private val renamedKeys: Map<String, String> = mapOf("ewe" to "ewe-go", "blink-charging-uk" to "blink-charging")

    fun currentKey(storedKey: String): String = renamedKeys[storedKey] ?: storedKey

    fun selection(keys: Set<String>): List<Network> = all.filter { it.key in keys }

    /** The network a site belongs to: by OCM operator id first, else by folded keyword. */
    fun resolve(site: ChargeSite): String? {
        site.operatorId?.let { id -> byOperatorId[id]?.let { return it.key } }
        val name = site.operator ?: return null
        val folded = OperatorKey.folded(name)
        return all.firstOrNull { n -> n.nameKeywords.any { containsWord(folded, it) } }?.key
    }

    private fun containsWord(haystack: String, keyword: String): Boolean {
        var from = 0
        while (true) {
            val idx = haystack.indexOf(keyword, from)
            if (idx < 0) return false
            val before = idx == 0 || !haystack[idx - 1].isLetterOrDigit()
            val end = idx + keyword.length
            val after = end >= haystack.length || !haystack[end].isLetterOrDigit()
            if (before && after) return true
            from = idx + 1
        }
    }
}
