package org.julakali.chargeahead.shared.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

// Charging-station local store (chargeSite) and which area was fetched when
// (tileCoverage, corridorCoverage).

@Entity(tableName = "chargeSite", indices = [Index("lat", "lon")])
data class ChargeSiteEntity(
    @PrimaryKey val id: String,
    val sourceId: String,
    val name: String,
    val operator: String?,
    val operatorId: Long? = null,
    val lat: Double,
    val lon: Double,
    // Connectors as a "type:kW:count" list; "count" may be empty.
    val connectors: String,
    // Postal address, if the source knows one.
    val street: String?,
    val postalCode: String?,
    val town: String?,
    val fetchedAtMillis: Long,
)

@Entity(tableName = "tileCoverage", primaryKeys = ["sourceId", "networkKey", "tileLat", "tileLon"])
data class TileCoverageEntity(
    val sourceId: String,
    val networkKey: String,
    // Tile indices on a 0.1° grid: floor(degree * 10).
    val tileLat: Long,
    val tileLon: Long,
    val fetchedAtMillis: Long,
)

// A fetched route buffer, too narrow to fully contain a tile. The box columns
// let SQL preselect the corridors near a query.
@Entity(tableName = "corridorCoverage", indices = [Index("sourceId", "networkKey")])
data class CorridorCoverageEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sourceId: String,
    val networkKey: String,
    // Route points as "lat,lon;lat,lon;…".
    val points: String,
    val bufferKm: Double,
    val south: Double,
    val west: Double,
    val north: Double,
    val east: Double,
    val fetchedAtMillis: Long,
)

// The tables are a regenerable cache: a schema bump just drops and refetches
// (fallbackToDestructiveMigration).
@Database(
    entities = [ChargeSiteEntity::class, TileCoverageEntity::class, CorridorCoverageEntity::class],
    version = 3,
    exportSchema = false,
)
@ConstructedBy(ChargeSiteDatabaseConstructor::class)
abstract class ChargeSiteDatabase : RoomDatabase() {
    abstract fun chargeSites(): ChargeSiteDao
}

// The actual is generated by Room's KSP.
@Suppress("KotlinNoActualForExpect")
expect object ChargeSiteDatabaseConstructor : RoomDatabaseConstructor<ChargeSiteDatabase> {
    override fun initialize(): ChargeSiteDatabase
}
