package de.autoapp.shared.db

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

// Charging-station local store, and the question of which area was fetched
// when. Two tables, because there are two questions: WHAT do we know
// (chargeSite) and FOR WHAT do we know that we know it completely
// (tileCoverage). Without the second, there'd be no way to tell whether an
// area has no charging station or whether nobody has ever checked there.

// Spatial queries always run over a rectangle — hence the (lat, lon) index.
@Entity(tableName = "chargeSite", indices = [Index("lat", "lon")])
data class ChargeSiteEntity(
    @PrimaryKey val id: String,
    val sourceId: String,
    val name: String,
    val operator: String?,
    val operatorId: Long? = null,
    val lat: Double,
    val lon: Double,
    // Connectors as a "type:kW:count" list. A dedicated table would be
    // cleaner, but connectors are never queried on their own: they're always
    // read and written together with their site. A join for that would be
    // effort without payoff. "count" may be empty — the sources often don't
    // state it.
    val connectors: String,
    // Postal address, if the source knows one. Individually nullable: the
    // sources fill in varying amounts of it.
    val street: String?,
    val postalCode: String?,
    val town: String?,
    val fetchedAtMillis: Long,
)

@Entity(tableName = "tileCoverage", primaryKeys = ["sourceId", "networkKey", "tileLat", "tileLon"])
data class TileCoverageEntity(
    val sourceId: String,
    val networkKey: String,
    // Tile indices on a 0.1° grid: floor(degree * 10).
    val tileLat: Long,
    val tileLon: Long,
    val fetchedAtMillis: Long,
)

// A fetched route buffer. It is far too narrow to fully contain a tile, so
// without this a route fetch would record nothing at all and every later
// route query would refetch. The box columns let SQL preselect the corridors
// near a query; the geometry check itself runs in Coverage.
@Entity(tableName = "corridorCoverage", indices = [Index("sourceId", "networkKey")])
data class CorridorCoverageEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val sourceId: String,
    val networkKey: String,
    // Route points as "lat,lon;lat,lon;…".
    val points: String,
    val bufferKm: Double,
    val south: Double,
    val west: Double,
    val north: Double,
    val east: Double,
    val fetchedAtMillis: Long,
)

// exportSchema = false for the same reason verifyMigrations was off under
// SQLDelight: a schema snapshot per version costs more than it buys. The
// tables are a regenerable cache, so a schema bump just drops and refetches
// — see fallbackToDestructiveMigration in DatabaseFactory. No hand-written
// Migration objects. Version 3 also discards the old tile coverage, which
// was recorded over bounding boxes and can't be trusted.
@Database(
    entities = [ChargeSiteEntity::class, TileCoverageEntity::class, CorridorCoverageEntity::class],
    version = 3,
    exportSchema = false,
)
@ConstructedBy(ChargeSiteDatabaseConstructor::class)
abstract class ChargeSiteDatabase : RoomDatabase() {
    abstract fun chargeSites(): ChargeSiteDao
}

// The actual is generated by Room's KSP — the documented KMP pattern.
@Suppress("KotlinNoActualForExpect")
expect object ChargeSiteDatabaseConstructor : RoomDatabaseConstructor<ChargeSiteDatabase> {
    override fun initialize(): ChargeSiteDatabase
}
